In [1]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
#Cargar archivo csv 
data = pd.read_csv('Mexico.csv')

#1 Host is Superhost

In [3]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

#Declaramos las variables dependientes e independientes para la regresión Logistica
Vars_Indep = df[['number_of_reviews', 'review_scores_rating', 
                 'review_scores_accuracy', 'review_scores_cleanliness', 
                 'review_scores_checkin', 'review_scores_communication', 
                 'review_scores_location', 'review_scores_value', 
                 'host_response_rate', 'host_acceptance_rate', 
                 'availability_365']]

Var_Dep = df['host_is_superhost']

In [4]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [5]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 't', 't', ..., 'f', 'f', 'f'], dtype=object)

In [6]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[4234  859]
 [1297 1585]]

Presicion del modelo:
0.6485270049099836

Exactitud del modelo:
0.7296551724137931

sensibilidad:
0.8313371293932849


#2 host_identity_verified

In [7]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['number_of_reviews', 'review_scores_rating', 
                 'host_acceptance_rate', 'availability_365']]

Var_Dep = df['host_identity_verified']

In [8]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [9]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], dtype=object)

In [10]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[   0  342]
 [   0 7633]]

Presicion del modelo:
0.957115987460815

Exactitud del modelo:
0.957115987460815

sensibilidad:
0.0


#3 has_availability

In [11]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['availability_30', 'availability_90', 'availability_365']]

Var_Dep = df['has_availability']

In [12]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [13]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], dtype=object)

In [14]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="t")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[   0    8]
 [   0 7967]]

Presicion del modelo:
0.9989968652037617

Exactitud del modelo:
0.9989968652037617

sensibilidad:
1.0


#4 instant_bookable

In [15]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['number_of_reviews', 'review_scores_rating', 
                 'host_listings_count', 'host_acceptance_rate', 
                 'availability_365', 'minimum_nights', 'accommodates', 'price', 'beds']]

Var_Dep = df['instant_bookable']

In [16]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [17]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 'f', 'f', 't'], dtype=object)

In [18]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[4060  793]
 [1355 1767]]

Presicion del modelo:
0.690234375

Exactitud del modelo:
0.7306583072100313

sensibilidad:
0.8365959200494539


#5 review_scores_rating

In [28]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

#Convertimos la variable a dicotomica
df["review_scores_rating"] = np.where(df["review_scores_rating"] >= 4, "Calificación alta", "Calificación media a baja")


In [29]:
# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['number_of_reviews', 
                 'review_scores_accuracy', 'review_scores_cleanliness', 
                 'review_scores_checkin', 'review_scores_communication', 
                 'review_scores_location', 'review_scores_value', 
                 'accommodates', 'minimum_nights', 'maximum_nights', 
                 'host_listings_count', 'host_total_listings_count']]

Var_Dep = df['review_scores_rating']

In [30]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [31]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Calificación alta', 'Calificación alta', 'Calificación alta', ...,
       'Calificación alta', 'Calificación alta', 'Calificación alta'],
      dtype=object)

In [32]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Calificación alta")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Calificación media a baja")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[7936    3]
 [  34    2]]

Presicion del modelo:
0.9957340025094102

Exactitud del modelo:
0.9953605015673981

sensibilidad:
0.05555555555555555


#6 number_of_reviews

In [33]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

media_reviews = df["number_of_reviews"].mean()

df["number_of_reviews"] = np.where(df["number_of_reviews"] >= media_reviews, 
                                   "Por encima de la media", 
                                   "Por debajo de la media")

In [34]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_90', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'accommodates', 'minimum_nights', 'maximum_nights', 'price']]

Var_Dep = df['number_of_reviews']

In [35]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [36]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Por debajo de la media', 'Por debajo de la media',
       'Por debajo de la media', ..., 'Por encima de la media',
       'Por debajo de la media', 'Por debajo de la media'], dtype=object)

In [37]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Por encima de la media")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Por debajo de la media")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[4914  335]
 [2248  478]]

Presicion del modelo:
0.5879458794587946

Exactitud del modelo:
0.6761128526645768

sensibilidad:
0.936178319679939


#7 price

In [38]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

df["price"] = df["price"]

# Convertimos la variable 'price' a dicotómica
df['price'] = df['price'].apply(lambda x: 'Precio Alto' if x >= 1500 else 'Precio Medio o Bajo')

In [39]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_90', 'availability_365', 
                 'accommodates', 'minimum_nights', 'maximum_nights', 'bathrooms', 
                 'bedrooms', 'beds','host_listings_count']]

Var_Dep = df['price']

In [40]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [41]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Precio Medio o Bajo', 'Precio Medio o Bajo',
       'Precio Medio o Bajo', ..., 'Precio Medio o Bajo',
       'Precio Medio o Bajo', 'Precio Alto'], dtype=object)

In [42]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Precio Medio o Bajo")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Precio Alto")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[1334 1423]
 [ 621 4597]]

Presicion del modelo:
0.7636212624584717

Exactitud del modelo:
0.7436990595611285

sensibilidad:
0.48385926731955026


#8 host_response_rate

In [43]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Convertimos la variable 'host_response_rate' a dicotómica
df['host_response_rate'] = df['host_response_rate'].apply(lambda x: 'Rango de respuesta alto' if x >= 0.7 else 'Rango de respuesta bajo')

In [44]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_90', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'host_acceptance_rate','price']]

Var_Dep = df['host_response_rate']

In [45]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [46]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Rango de respuesta alto', 'Rango de respuesta alto',
       'Rango de respuesta alto', ..., 'Rango de respuesta alto',
       'Rango de respuesta alto', 'Rango de respuesta alto'], dtype=object)

In [47]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Rango de respuesta bajo")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Rango de respuesta alto")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[7813    0]
 [ 162    0]]

Presicion del modelo:
0.0

Exactitud del modelo:
0.9796865203761755

sensibilidad:
1.0


c:\Users\yulia\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


#9 host_acceptance_rate

In [48]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Convertimos la variable 'host_response_rate' a dicotómica
df['host_acceptance_rate'] = df['host_acceptance_rate'].apply(lambda x: 'Rango de aceptacion alto' if x >= 0.7 else 'Rango de aceptacion bajo')

In [49]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_90', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'host_response_rate','price']]

Var_Dep = df['host_acceptance_rate']

In [50]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [51]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Rango de aceptacion alto', 'Rango de aceptacion alto',
       'Rango de aceptacion alto', ..., 'Rango de aceptacion alto',
       'Rango de aceptacion alto', 'Rango de aceptacion alto'],
      dtype=object)

In [52]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Rango de aceptacion bajo")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Rango de aceptacion alto")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[7494   22]
 [ 448   11]]

Presicion del modelo:
0.3333333333333333

Exactitud del modelo:
0.9410658307210031

sensibilidad:
0.9970729111229377


#10 availability_30

In [53]:
# Hacemos una copia del DataFrame para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Convertimos la variable 'availability_30' a dicotómica
df['availability_30'] = df['availability_30'].apply(lambda x: 'Alta disponibilidad' if x >= 15 else 'Baja disponibilidad')


In [54]:
# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['availability_90', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'host_response_rate', 'price']]

Var_Dep = df['availability_30']

In [55]:
# Redefinimos las variables
x = Vars_Indep
y = Var_Dep

# Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=None)

# Se escalan todos los datos
escalar = StandardScaler()

# Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

# Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

# Entrenamos el modelo
algoritmo.fit(X_train, y_train)


LogisticRegression()

In [56]:
# Realizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['Baja disponibilidad', 'Baja disponibilidad',
       'Baja disponibilidad', ..., 'Baja disponibilidad',
       'Baja disponibilidad', 'Baja disponibilidad'], dtype=object)

In [57]:
# Verificamos la matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

# Calculo la precisión del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="Baja disponibilidad")
print('\nPrecisión del modelo:')
print(precision)

# Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

# Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Alta disponibilidad")
print('\nSensibilidad:')
print(sensibilidad)

Matriz de Confusión:
[[3781  401]
 [ 519 3274]]

Precisión del modelo:
0.8908843537414965

Exactitud del modelo:
0.8846394984326019

Sensibilidad:
0.9041128646580583
