In [2]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
#Cargar archivo csv 
data = pd.read_csv('Amsterdam.csv')
data = data.drop(columns = ["Unnamed: 0.1", "Unnamed: 0"])

In [4]:
# Convertimos la variable a tipo númerico

data['host_acceptance_rate'] = data['host_acceptance_rate'].str.rstrip('%').astype(int)
data['host_response_rate'] = data['host_response_rate'].str.rstrip('%').astype(int)

#1 Host is Superhost

In [12]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

#Declaramos las variables dependientes e independientes para la regresión Logistica
Vars_Indep = df[['number_of_reviews', 'review_scores_rating', 
                 'review_scores_accuracy', 'review_scores_cleanliness', 
                 'review_scores_checkin', 'review_scores_communication', 
                 'review_scores_location', 'review_scores_value', 
                 'host_response_rate', 'host_acceptance_rate', 
                 'availability_365']]

Var_Dep = df['host_is_superhost']

In [13]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [15]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], dtype=object)

In [16]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[2338   83]
 [ 354  123]]

Presicion del modelo:
0.5970873786407767

Exactitud del modelo:
0.8492063492063492

sensibilidad:
0.9657166460140438


#2 host_identity_verified

In [18]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['number_of_reviews', 'review_scores_rating', 
                 'host_acceptance_rate', 'availability_365']]

Var_Dep = df['host_identity_verified']

In [19]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [20]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], dtype=object)

In [21]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[   0   91]
 [   0 2807]]

Presicion del modelo:
0.9685990338164251

Exactitud del modelo:
0.9685990338164251

sensibilidad:
0.0


#3 has_availability

In [23]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['availability_30', 'availability_90', 'availability_365']]

Var_Dep = df['has_availability']

In [24]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [25]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], dtype=object)

In [26]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="t")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[   0  112]
 [   0 2786]]

Presicion del modelo:
0.961352657004831

Exactitud del modelo:
0.961352657004831

sensibilidad:
1.0


#4 instant_bookable

In [27]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['number_of_reviews', 'review_scores_rating', 
                 'host_listings_count', 'host_acceptance_rate', 
                 'availability_365', 'minimum_nights', 'accommodates', 'price', 'beds']]

Var_Dep = df['instant_bookable']

In [28]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [29]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], dtype=object)

In [30]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[2388   35]
 [ 351  124]]

Presicion del modelo:
0.779874213836478

Exactitud del modelo:
0.8668046928916494

sensibilidad:
0.9855550969872059


#5 review_scores_rating

In [41]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Sacamos la media de esa columna para definir los valores 
media = df["review_scores_rating"].mean()

#Convertimos la variable a dicotomica
df["review_scores_rating"] = np.where(df["review_scores_rating"] >= 4.8, "Calificación alta", "Calificación media a baja")


In [42]:
# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['number_of_reviews', 
                 'review_scores_accuracy', 'review_scores_cleanliness', 
                 'review_scores_checkin', 'review_scores_communication', 
                 'review_scores_location', 'review_scores_value', 
                 'accommodates', 'minimum_nights', 'maximum_nights', 
                 'host_listings_count', 'host_total_listings_count']]

Var_Dep = df['review_scores_rating']

In [43]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [45]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Calificación alta', 'Calificación alta', 'Calificación alta', ...,
       'Calificación alta', 'Calificación alta', 'Calificación alta'],
      dtype=object)

In [46]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Calificación alta")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Calificación media a baja")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[2267  118]
 [ 258  255]]

Presicion del modelo:
0.8978217821782178

Exactitud del modelo:
0.8702553485162181

sensibilidad:
0.49707602339181284


#6 number_of_reviews

In [47]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

media_reviews = df["number_of_reviews"].mean()

df["number_of_reviews"] = np.where(df["number_of_reviews"] >= media_reviews, 
                                   "Por encima de la media", 
                                   "Por debajo de la media")

In [49]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_90', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'accommodates', 'minimum_nights', 'maximum_nights', 'price']]

Var_Dep = df['number_of_reviews']

In [50]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [51]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Por debajo de la media', 'Por debajo de la media',
       'Por debajo de la media', ..., 'Por debajo de la media',
       'Por debajo de la media', 'Por debajo de la media'], dtype=object)

In [52]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Por encima de la media")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Por debajo de la media")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[2046    0]
 [ 852    0]]

Presicion del modelo:
0.0

Exactitud del modelo:
0.7060041407867494

sensibilidad:
1.0


c:\Users\yulia\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


#7 price

In [8]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

df["price"] = df["price"] * 22.07

# Sacamos la media de esa columna para definir los valores 
media = df["price"].mean()

# Convertimos la variable 'price' a dicotómica
df['price'] = df['price'].apply(lambda x: 'Precio Alto' if x >= 5500 else 'Precio Medio o Bajo')

In [9]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_90', 'availability_365', 
                 'accommodates', 'minimum_nights', 'maximum_nights', 'bathrooms', 
                 'bedrooms', 'beds','host_listings_count']]

Var_Dep = df['price']

In [10]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [11]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Precio Medio o Bajo', 'Precio Alto', 'Precio Alto', ...,
       'Precio Alto', 'Precio Alto', 'Precio Alto'], dtype=object)

In [12]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Precio Medio o Bajo")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Precio Alto")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[1693  221]
 [ 515  469]]

Presicion del modelo:
0.6797101449275362

Exactitud del modelo:
0.746031746031746

sensibilidad:
0.8845350052246604


#8 host_response_rate

In [58]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Convertimos la variable 'host_response_rate' a dicotómica
df['host_response_rate'] = df['host_response_rate'].apply(lambda x: 'Rango de respuesta alto' if x >= 0.7 else 'Rango de respuesta bajo')

In [59]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_90', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'host_acceptance_rate','price']]

Var_Dep = df['host_response_rate']

In [60]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [61]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Rango de respuesta bajo', 'Rango de respuesta alto',
       'Rango de respuesta alto', ..., 'Rango de respuesta alto',
       'Rango de respuesta bajo', 'Rango de respuesta bajo'], dtype=object)

In [62]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Rango de respuesta bajo")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Rango de respuesta alto")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[1706  193]
 [ 370  629]]

Presicion del modelo:
0.7652068126520681

Exactitud del modelo:
0.805728088336784

sensibilidad:
0.8983675618746709


#9 host_acceptance_rate

In [63]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Convertimos la variable 'host_response_rate' a dicotómica
df['host_acceptance_rate'] = df['host_acceptance_rate'].apply(lambda x: 'Rango de aceptacion alto' if x >= 0.7 else 'Rango de aceptacion bajo')

In [65]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_90', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'host_response_rate','price']]

Var_Dep = df['host_acceptance_rate']

In [66]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [67]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Rango de aceptacion alto', 'Rango de aceptacion alto',
       'Rango de aceptacion bajo', ..., 'Rango de aceptacion alto',
       'Rango de aceptacion alto', 'Rango de aceptacion bajo'],
      dtype=object)

In [68]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Rango de aceptacion bajo")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Rango de aceptacion alto")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[1849  366]
 [ 106  577]]

Presicion del modelo:
0.6118769883351007

Exactitud del modelo:
0.8371290545203589

sensibilidad:
0.834762979683973


#10 availability_30

In [69]:
# Hacemos una copia del DataFrame para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Convertimos la variable 'availability_30' a dicotómica
df['availability_30'] = df['availability_30'].apply(lambda x: 'Alta disponibilidad' if x >= 15 else 'Baja disponibilidad')


In [70]:
# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['availability_90', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'host_response_rate', 'price']]

Var_Dep = df['availability_30']

In [72]:
# Redefinimos las variables
x = Vars_Indep
y = Var_Dep

# Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=None)

# Se escalan todos los datos
escalar = StandardScaler()

# Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

# Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

# Entrenamos el modelo
algoritmo.fit(X_train, y_train)


LogisticRegression()

In [73]:
# Realizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['Baja disponibilidad', 'Baja disponibilidad',
       'Baja disponibilidad', ..., 'Baja disponibilidad',
       'Baja disponibilidad', 'Baja disponibilidad'], dtype=object)

In [74]:
# Verificamos la matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

# Calculo la precisión del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="Baja disponibilidad")
print('\nPrecisión del modelo:')
print(precision)

# Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

# Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Alta disponibilidad")
print('\nSensibilidad:')
print(sensibilidad)

Matriz de Confusión:
[[   0   70]
 [   0 2828]]

Precisión del modelo:
0.9758454106280193

Exactitud del modelo:
0.9758454106280193

Sensibilidad:
0.0
