In [1]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
#Cargar archivo csv desde seaborn
data = pd.read_csv("Hong Kong.csv")

#1 Host is Superhost

In [4]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

#Declaramos las variables dependientes e independientes para la regresión Logistica
Vars_Indep = df[['number_of_reviews', 'reviews_per_month', 'review_scores_rating', 
                 'review_scores_accuracy', 'review_scores_cleanliness', 
                 'review_scores_checkin', 'review_scores_communication', 
                 'review_scores_location', 'review_scores_value', 
                 'host_response_rate', 'host_acceptance_rate', 
                 'availability_365']]

Var_Dep = df['host_is_superhost']

In [5]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [166]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 'f', 'f', ..., 't', 'f', 'f'], shape=(2016,), dtype=object)

In [ ]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[1714   48]
 [ 179   75]]

Presicion del modelo:
0.6097560975609756

Exactitud del modelo:
0.8874007936507936

sensibilidad:
0.9727582292849035


#2 host_identity_verified

In [ ]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['number_of_reviews', 'review_scores_rating', 'reviews_per_month', 
                 'host_acceptance_rate', 'availability_365']]

Var_Dep = df['host_identity_verified']

In [171]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [172]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], shape=(2016,), dtype=object)

In [173]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[   0   67]
 [   0 1949]]

Presicion del modelo:
0.966765873015873

Exactitud del modelo:
0.966765873015873

sensibilidad:
0.0


#3 has_availability

In [13]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['availability_30', 'availability_60', 'availability_90', 'availability_365']]

Var_Dep = df['has_availability']

In [14]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [15]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], shape=(2016,), dtype=object)

In [17]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="t")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[   0   11]
 [   0 2005]]

Presicion del modelo:
0.9945436507936508

Exactitud del modelo:
0.9945436507936508

sensibilidad:
1.0


#4 instant_bookable

In [ ]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['number_of_reviews', 'reviews_per_month', 'review_scores_rating', 
                 'host_listings_count', 'host_acceptance_rate', 
                 'availability_365', 'minimum_nights', 'accommodates', 'price', 'beds']]

Var_Dep = df['instant_bookable']

In [208]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [209]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 'f', 't', ..., 'f', 'f', 'f'], shape=(2016,), dtype=object)

In [210]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[1438   87]
 [ 309  182]]

Presicion del modelo:
0.6765799256505576

Exactitud del modelo:
0.8035714285714286

sensibilidad:
0.9429508196721311


#5 review_scores_rating

In [ ]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

#Convertimos la variable a dicotomica
df["review_scores_rating"] = np.where(df["review_scores_rating"] >= 4, "Calificación alta", "Calificación media a baja")

In [ ]:
# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['number_of_reviews', 'reviews_per_month', 
                 'review_scores_accuracy', 'review_scores_cleanliness', 
                 'review_scores_checkin', 'review_scores_communication', 
                 'review_scores_location', 'review_scores_value', 
                 'accommodates', 'minimum_nights', 'maximum_nights', 
                 'host_listings_count', 'host_total_listings_count']]

Var_Dep = df['review_scores_rating']

In [31]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [32]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Calificación alta', 'Calificación alta', 'Calificación alta', ...,
       'Calificación alta', 'Calificación alta', 'Calificación alta'],
      shape=(2016,), dtype=object)

In [35]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Calificación alta")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Calificación media a baja")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[1944   10]
 [  20   42]]

Presicion del modelo:
0.9898167006109979

Exactitud del modelo:
0.9851190476190477

sensibilidad:
0.6774193548387096


#6 number_of_reviews

In [ ]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

media_reviews = df["number_of_reviews"].mean()

df["number_of_reviews"] = np.where(df["number_of_reviews"] >= media_reviews, 
                                   "Por encima de la media", 
                                   "Por debajo de la media")

In [ ]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_60', 'availability_90', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'accommodates', 'minimum_nights', 'maximum_nights', 'price']]

Var_Dep = df['number_of_reviews']

In [52]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [53]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Por debajo de la media', 'Por debajo de la media',
       'Por debajo de la media', ..., 'Por debajo de la media',
       'Por debajo de la media', 'Por debajo de la media'],
      shape=(2016,), dtype=object)

In [55]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Por encima de la media")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Por debajo de la media")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[1584   44]
 [ 297   91]]

Presicion del modelo:
0.674074074074074

Exactitud del modelo:
0.8308531746031746

sensibilidad:
0.972972972972973


#7 price

In [56]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

df["price"] = df["price"] * 2.70

# Convertimos la variable 'price' a dicotómica
df['price'] = df['price'].apply(lambda x: 'Precio Alto' if x >= 1500 else 'Precio Medio o Bajo')

In [58]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_60', 'availability_90', 'availability_365', 
                 'accommodates', 'minimum_nights', 'maximum_nights', 'bathrooms', 
                 'bedrooms', 'beds','host_listings_count']]

Var_Dep = df['price']

In [59]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [60]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Precio Alto', 'Precio Medio o Bajo', 'Precio Medio o Bajo', ...,
       'Precio Medio o Bajo', 'Precio Medio o Bajo',
       'Precio Medio o Bajo'], shape=(2016,), dtype=object)

In [61]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Precio Medio o Bajo")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Precio Alto")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[ 390  376]
 [ 124 1126]]

Presicion del modelo:
0.7496671105193076

Exactitud del modelo:
0.751984126984127

sensibilidad:
0.5091383812010444


#8 host_response_rate

In [62]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Convertimos la variable 'host_response_rate' a dicotómica
df['host_response_rate'] = df['host_response_rate'].apply(lambda x: 'Rango de respuesta alto' if x >= 0.7 else 'Rango de respuesta bajo')

In [66]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_60', 'availability_90', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'host_acceptance_rate','price']]

Var_Dep = df['host_response_rate']

In [67]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [68]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Rango de respuesta alto', 'Rango de respuesta alto',
       'Rango de respuesta alto', ..., 'Rango de respuesta alto',
       'Rango de respuesta alto', 'Rango de respuesta alto'],
      shape=(2016,), dtype=object)

In [69]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Rango de respuesta bajo")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Rango de respuesta alto")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[1823   25]
 [ 145   23]]

Presicion del modelo:
0.4791666666666667

Exactitud del modelo:
0.9156746031746031

sensibilidad:
0.9864718614718615


#9 host_acceptance_rate

In [71]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Convertimos la variable 'host_response_rate' a dicotómica
df['host_acceptance_rate'] = df['host_acceptance_rate'].apply(lambda x: 'Rango de aceptacion alto' if x >= 0.7 else 'Rango de aceptacion bajo')

In [72]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_60', 'availability_90', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'host_response_rate','price']]

Var_Dep = df['host_acceptance_rate']

In [73]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [74]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Rango de aceptacion alto', 'Rango de aceptacion alto',
       'Rango de aceptacion bajo', ..., 'Rango de aceptacion alto',
       'Rango de aceptacion alto', 'Rango de aceptacion alto'],
      shape=(2016,), dtype=object)

In [75]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Rango de aceptacion bajo")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Rango de aceptacion alto")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[1009  110]
 [ 243  654]]

Presicion del modelo:
0.856020942408377

Exactitud del modelo:
0.8249007936507936

sensibilidad:
0.9016979445933869


#10 availability_30

In [78]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()


# Convertimos la variable 'availability_30' a dicotómica
df['availability_30'] = df['availability_30'].apply(lambda x: 'Alta disponibilidad' if x >= 15 else 'Baja disponibilidad')

In [79]:
# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['availability_90', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'host_response_rate', 'price']]

Var_Dep = df['availability_30']

In [80]:
# Redefinimos las variables
x = Vars_Indep
y = Var_Dep

# Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=None)

# Se escalan todos los datos
escalar = StandardScaler()

# Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

# Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

# Entrenamos el modelo
algoritmo.fit(X_train, y_train)


LogisticRegression()

In [81]:
# Realizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['Alta disponibilidad', 'Alta disponibilidad',
       'Baja disponibilidad', ..., 'Alta disponibilidad',
       'Baja disponibilidad', 'Alta disponibilidad'],
      shape=(2016,), dtype=object)

In [82]:
# Verificamos la matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

# Calculo la precisión del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="Baja disponibilidad")
print('\nPrecisión del modelo:')
print(precision)

# Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

# Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Alta disponibilidad")
print('\nSensibilidad:')
print(sensibilidad)

Matriz de Confusión:
[[1185   45]
 [ 111  675]]

Precisión del modelo:
0.9375

Exactitud del modelo:
0.9226190476190477

Sensibilidad:
0.9634146341463414
