In [50]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [51]:
#Cargar archivo csv desde seaborn
data = pd.read_csv("ValoresAtipicosMilan.csv")

#1 Host is Superhost

In [52]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

#Declaramos las variables dependientes e independientes para la regresión Logistica
Vars_Indep = df[['number_of_reviews', 'review_scores_rating', 
                 'review_scores_accuracy', 'review_scores_cleanliness', 
                 'review_scores_checkin', 'review_scores_communication', 
                 'review_scores_location', 'review_scores_value', 
                 'host_response_rate', 'host_acceptance_rate', 
                 'availability_365']]

Var_Dep = df['host_is_superhost']

In [53]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [54]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], dtype=object)

In [55]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[4882  272]
 [1276  682]]

Presicion del modelo:
0.7148846960167715

Exactitud del modelo:
0.7823397075365579

sensibilidad:
0.9472254559565386


#2 host_identity_verified

In [56]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['number_of_reviews', 'review_scores_rating', 
                 'host_acceptance_rate', 'availability_365']]

Var_Dep = df['host_identity_verified']

In [57]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [58]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], dtype=object)

In [59]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[   0  427]
 [   0 6685]]

Presicion del modelo:
0.9399606299212598

Exactitud del modelo:
0.9399606299212598

sensibilidad:
0.0


#3 has_availability

In [60]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['availability_30', 'availability_90', 'availability_365']]

Var_Dep = df['has_availability']

In [61]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [62]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], dtype=object)

In [63]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="t")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[   0    4]
 [   0 7108]]

Presicion del modelo:
0.999437570303712

Exactitud del modelo:
0.999437570303712

sensibilidad:
1.0


#4 instant_bookable

In [64]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['number_of_reviews', 'review_scores_rating', 
                 'host_listings_count', 'host_acceptance_rate', 
                 'availability_365', 'minimum_nights', 'accommodates', 'price', 'beds']]

Var_Dep = df['instant_bookable']

In [65]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [66]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 'f', 't', ..., 't', 'f', 't'], dtype=object)

In [67]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[2985  834]
 [ 596 2697]]

Presicion del modelo:
0.7638062871707731

Exactitud del modelo:
0.7989313835770528

sensibilidad:
0.781618224666143


#5 review_scores_rating

In [68]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

#Convertimos la variable a dicotomica
df["review_scores_rating"] = np.where(df["review_scores_rating"] >= 4, "Calificación alta", "Calificación media a baja")

In [69]:
# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['number_of_reviews',
                 'review_scores_accuracy', 'review_scores_cleanliness', 
                 'review_scores_checkin', 'review_scores_communication', 
                 'review_scores_location', 'review_scores_value', 
                 'accommodates', 'minimum_nights', 'maximum_nights', 
                 'host_listings_count', 'host_total_listings_count']]

Var_Dep = df['review_scores_rating']

In [70]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [71]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Calificación alta', 'Calificación alta', 'Calificación alta', ...,
       'Calificación alta', 'Calificación alta', 'Calificación alta'],
      dtype=object)

In [72]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Calificación alta")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Calificación media a baja")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[6980   24]
 [  79   29]]

Presicion del modelo:
0.9888086131180054

Exactitud del modelo:
0.9855174353205849

sensibilidad:
0.26851851851851855


#6 number_of_reviews

In [73]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

media_reviews = df["number_of_reviews"].mean()

df["number_of_reviews"] = np.where(df["number_of_reviews"] >= media_reviews, 
                                   "Por encima de la media", 
                                   "Por debajo de la media")

In [74]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_30', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'accommodates', 'minimum_nights', 'maximum_nights', 'price']]

Var_Dep = df['number_of_reviews']

In [75]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [76]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Por debajo de la media', 'Por debajo de la media',
       'Por debajo de la media', ..., 'Por debajo de la media',
       'Por debajo de la media', 'Por debajo de la media'], dtype=object)

In [77]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Por encima de la media")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Por debajo de la media")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[4961   31]
 [2086   34]]

Presicion del modelo:
0.5230769230769231

Exactitud del modelo:
0.702334083239595

sensibilidad:
0.9937900641025641


#7 price

In [78]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

#Convertimos a pesos mexicamos
df["price"] = df["price"] * 22.01

media_precio = df['price'].mean()
print(media_precio)


3998.1281228507582


In [79]:
# Convertimos la variable 'price' a dicotómica
df['price'] = df['price'].apply(lambda x: 'Precio Alto' if x >= 4000 else 'Precio Medio o Bajo')

In [80]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_90', 'availability_365', 
                 'accommodates', 'minimum_nights', 'maximum_nights', 'bathrooms', 
                 'bedrooms', 'beds','host_listings_count']]

Var_Dep = df['price']

In [81]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [82]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Precio Medio o Bajo', 'Precio Alto', 'Precio Medio o Bajo', ...,
       'Precio Medio o Bajo', 'Precio Medio o Bajo', 'Precio Alto'],
      dtype=object)

In [83]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Precio Medio o Bajo")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Precio Alto")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[ 726 1717]
 [ 462 4207]]

Presicion del modelo:
0.7101620526671168

Exactitud del modelo:
0.6936164229471317

sensibilidad:
0.29717560376586166


#8 host_response_rate

In [115]:
#Verificar los valores sin repetirse de una columna 
df = data.copy()
unico = np.unique([df['host_response_rate']])
unico

array([0.46      , 0.47      , 0.5       , 0.53      , 0.55      ,
       0.56      , 0.57      , 0.58      , 0.6       , 0.61      ,
       0.63      , 0.64      , 0.65      , 0.67      , 0.68      ,
       0.69      , 0.7       , 0.71      , 0.72      , 0.73      ,
       0.74      , 0.75      , 0.77      , 0.78      , 0.79      ,
       0.8       , 0.82      , 0.83      , 0.84      , 0.85      ,
       0.86      , 0.87      , 0.88      , 0.89      , 0.9       ,
       0.91      , 0.92      , 0.93      , 0.94      , 0.94206539,
       0.95      , 0.96      , 0.97      , 0.98      , 0.99      ,
       1.        ])

In [116]:
# Convertimos la variable 'host_response_rate' a dicotómica
df['host_response_rate'] = df['host_response_rate'].apply(lambda x: 'Rango de respuesta alto' if x >= 0.7 else 'Rango de respuesta bajo')

In [117]:
unico = np.unique([df['host_response_rate']])
unico

array(['Rango de respuesta alto', 'Rango de respuesta bajo'], dtype=object)

In [118]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_90', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'host_acceptance_rate','price']]

Var_Dep = df['host_response_rate']

In [119]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None, stratify=y)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [120]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Rango de respuesta alto', 'Rango de respuesta alto',
       'Rango de respuesta alto', ..., 'Rango de respuesta alto',
       'Rango de respuesta alto', 'Rango de respuesta alto'], dtype=object)

In [121]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Rango de respuesta bajo")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Rango de respuesta alto")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[6970    0]
 [ 142    0]]

Presicion del modelo:
0.0

Exactitud del modelo:
0.9800337457817773

sensibilidad:
1.0


c:\Python\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [104]:
print(np.unique(y_pred, return_counts=True))

(array(['Rango de respuesta alto'], dtype=object), array([7112], dtype=int64))


#9 host_acceptance_rate

In [89]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()

# Convertimos la variable 'host_response_rate' a dicotómica
df['host_acceptance_rate'] = df['host_acceptance_rate'].apply(lambda x: 'Rango de aceptacion alto' if x >= 0.7 else 'Rango de aceptacion bajo')

In [90]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep = df[['availability_30', 'availability_90', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'host_response_rate','price']]

Var_Dep = df['host_acceptance_rate']

In [91]:
#Redefinimos las variables
x= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba, utilizaremos ...
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [92]:
#Realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['Rango de aceptacion alto', 'Rango de aceptacion alto',
       'Rango de aceptacion alto', ..., 'Rango de aceptacion alto',
       'Rango de aceptacion alto', 'Rango de aceptacion alto'],
      dtype=object)

In [93]:
#Verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Rango de aceptacion bajo")
print('\nPresicion del modelo:')
print(precision)

#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Rango de aceptacion alto")
print('\nsensibilidad:')
print(sensibilidad)

Matriz de Confusion:
[[6367   25]
 [ 701   19]]

Presicion del modelo:
0.4318181818181818

Exactitud del modelo:
0.8979190101237345

sensibilidad:
0.9960888610763454


#10 availability_30

In [94]:
#Hacemos una copia del dataframe para que los datos no se vean alterados si hacemos un cambio
df = data.copy()


# Convertimos la variable 'availability_30' a dicotómica
df['availability_30'] = df['availability_30'].apply(lambda x: 'Alta disponibilidad' if x >= 15 else 'Baja disponibilidad')

In [95]:
# Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep = df[['availability_90', 'availability_365', 
                 'host_listings_count', 'host_total_listings_count', 
                 'host_response_rate', 'price']]

Var_Dep = df['availability_30']

In [96]:
# Redefinimos las variables
x = Vars_Indep
y = Var_Dep

# Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=None)

# Se escalan todos los datos
escalar = StandardScaler()

# Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

# Definimos el algoritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

# Entrenamos el modelo
algoritmo.fit(X_train, y_train)


LogisticRegression()

In [97]:
# Realizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['Baja disponibilidad', 'Baja disponibilidad',
       'Baja disponibilidad', ..., 'Baja disponibilidad',
       'Baja disponibilidad', 'Baja disponibilidad'], dtype=object)

In [98]:
# Verificamos la matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

# Calculo la precisión del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="Baja disponibilidad")
print('\nPrecisión del modelo:')
print(precision)

# Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:')
print(exactitud)

# Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Alta disponibilidad")
print('\nSensibilidad:')
print(sensibilidad)

Matriz de Confusión:
[[1918  270]
 [ 265 4659]]

Precisión del modelo:
0.9452221545952526

Exactitud del modelo:
0.9247750281214848

Sensibilidad:
0.876599634369287
